# Generated by Django 5.1.4 on 2025-01-14 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("st_client", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConnectionHistory",
        ),
    ]
