# Generated by Django 5.1.4 on 2025-01-14 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("host", models.CharField(max_length=100)),
                ("port", models.IntegerField()),
                (
                    "protocol",
                    models.CharField(
                        choices=[("WS", "WebSocket"), ("WSS", "WebSocket Secure")],
                        default="WS",
                        max_length=3,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("offline", "Offline"),
                            ("unstable", "Unstable"),
                        ],
                        default="offline",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
