# Generated by Django 5.1.4 on 2025-01-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("st_teamserver", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamServer",
        ),
    ]
